relay: update documentation
tarantool/tarantool-internals pull request #37
Opened 2022-09-26 14:05 UTC by Serpentian

According to the fact that no changes were done to the docs for more than 2 years, some parts of it are not up to date anymore.

Let's update them.

2022-09-30 15:06 UTC, sergepetrenko requested changes
Hi! Thanks for working on this, good job!
My comments are below.

2022-09-30 15:06 UTC, sergepetrenko commented on source/relay.rst
> +fetches rows up to this position, it enters read-write mode.
Let's better say
"When replica fetches rows up to this position, it knows it is synced with the master".

Whether it will enter read-write mode after that or not depends on its `replication_connect_quorum` setting and other remote peers listed in its `box.cfg.replication`.

2022-10-03 09:24 UTC, Serpentian commented on source/relay.rst
> +    - `current_vclock` - master's vclock after final stage.
You are right, it's better to describe it in `replication` doc. Let's also give a reference to it in `relay`.

2022-10-03 09:28 UTC, Serpentian commented on source/relay.rst
> +remote replica.
Fixed. It was actually stated above in the general overview of the JOIN protocol. Removed that part (we'll include it in `replication` doc), so let's add what rows do we mean right here

2022-10-03 10:24 UTC, sergepetrenko requested changes
Thanks for the fixes!
Please, take a look at some extra comments.

2022-10-03 10:24 UTC, sergepetrenko commented on source/relay.rst
> +         /* Retry if needed */
It's not about retrying.

Here's how this system works. The same (or similar) constructions can be found between "applier thread" and applier fiber in tx thread, iproto and tx (iproto kharon).

The idea of `msg->route` is as follows: it's a sequence of functions and destinations where these functions should be executed.
`route[0].f` is the function this message carries to the other side of cbus.
`route[0].pipe` is where the message will go next. After `route[0].f` is executed in the destination. In most cases the message goes back to the initial caller, hence `relay->tx_pipe` in this example.
`route[1].f` is the function to execute on the second hop (usually in the initial caller, like here).
`route[1].pipe` is where to push the message next. Nowhere, in this case, meaning mesage processing is finished after the message returns to tx.

A lot of times `cbus` serves as means to notify one thread of some news happening in another thread.
Noone limits the pace at which the notifications appear. For example, `relay_push_raft` may be triggered tens of times a second, if raft terms are bumped fast enough. We don't want to dynamically allocate tens of cbus messages in such cases, and we are fine with losing older messages as long as we deliver newer ones.

In such cases we usually pre-allocate 2 messages (like we did here in relay structure: `relay->tx.raft_msgs`).
At any given point in time, at least one of the two messages resides in sender thread (tx), it receives any updates that arrive while the other message is somewhere between sender and receiver (tx and relay).

As soon as the traveling message returns to sender, it has to check if the other message has new updates. In case it does, it has to be sent again.

Let's see how this works in code:

```c
relay_push_raft()
    msg = relay->tx.raft_msgs[relay->tx.raft_ready_msg]; // choose the idle message.
    msg->req = *req; // update the request it holds. The new request overwrites the old one. It's fine for raft and for many other applications.
    ...
    relay->tx.is_raft_push_pending = true;
    relay_push_raft_msg(...);
        if (relay->tx.is_raft_push_sent) // do not push the second message if the first one already is en route. Otherwise there will be no idle message to store incoming updates.
            return
        ...
```

Now, once the first message returns to tx thread, it executes
```c
tx_raft_msg_return()
    relay->is_raft_push_sent = false; // no message is en route.
    if (relay->tx.is_raft_push_pending) // other message received updates while this one was travelling
        relay_push_raft_msg(...)
```

2022-10-06 21:34 UTC, Serpentian commented on source/relay.rst
> +function ``IPROTO_JOIN`` code is sent. It initializes JOIN procedure
Let's just say that we 'perform joining procedure if needed' and describe when it's "needed" in replication internal docs, as there's a part, which describes `applier_f`, where join procedure is initialized.

Actually it seemed to me that we join only when no replicaset uuid was found in local files during recovery. I didn't really get what you mean by `master doesn't have the relevant journal files so that replica could continue subscription from where it left off previously`. Cannot find it in code neither.

2022-10-06 21:34 UTC, Serpentian commented on source/relay.rst
Sounds good. We can just add a new comment in the beginning of every code block. I'm pretty tired of grepping.

2022-10-06 21:34 UTC, Serpentian commented on source/relay.rst
> +            // relay_initial_join() code
Fixed

2022-10-06 21:34 UTC, Serpentian commented on source/relay.rst
> +SUBSCRIBE request from remote peer (see ``applier_f()`` at the
Ok, let's say like that. But I cannot really find where the connection is closed. After joining in `applier_f` we immediately subscribe, connection is not closed if there's was no error.

2022-10-06 21:34 UTC, Serpentian commented on source/relay.rst
>  the ``relay_process_wal_event`` will be called which calls
Fixed

2022-10-06 21:35 UTC, Serpentian commented on source/relay.rst
> +         /* Retry if needed */
Thanks a lot, now I really got it

2022-10-10 14:43 UTC, sergepetrenko commented on source/relay.rst
Nice.

2022-10-10 14:46 UTC, sergepetrenko commented on source/relay.rst
> +are some records which are not yet set to that replica. This way final stage
typo: "not yet set" -> "not yet sent"

2022-10-10 14:46 UTC, sergepetrenko commented on source/relay.rst
> +SUBSCRIBE request from remote peer (see ``applier_f()`` at the
Hm. Yes, I see.
I'm not sure about that. Probably the connection isn't closed indeed.
But I'm confused by `net_end_join` in `box/iproto.cc`. It seems master will close the connection is replica isn't in time to send the subscribe request.

2022-10-10 14:52 UTC, sergepetrenko commented on source/relay.rst
> +         /* Retry if needed */
No problem

2022-10-12 03:22 UTC, Serpentian commented on source/relay.rst
> +SUBSCRIBE request from remote peer (see ``applier_f()`` at the
Let's not say that the connection is closed because AFAICS it's done by the master only when error occured while enqueuing requests which were read up (invalid MessagePack or memory error). It's not done by the replica either if join procedure was successfull.

2022-10-12 03:24 UTC, Serpentian commented on source/relay.rst
> +are some records which are not yet set to that replica. This way final stage
Fixed

2022-10-12 13:36 UTC, sergepetrenko commented on source/relay.rst
> +SUBSCRIBE request from remote peer (see ``applier_f()`` at the
Ok, agreed.

2022-10-17 08:04 UTC, merged