wal: update documentation
tarantool/tarantool-internals pull request #38
Opened 2022-10-03 10:43 UTC by Serpentian

This commit updates obsolete parts of the code, adds more extensive description of its work, moves documentation related to communication bus (cbus) to the seperate page, as it's widely used not only in wal description but also in relay.

Co-authored-by: Sergey Petrenko <sergepetrenko@tarantool.org>

2022-10-10 15:20 UTC, sergepetrenko requested changes
Thanks!
I like the cbus description. Please find some comments below.

2022-10-10 15:20 UTC, sergepetrenko commented on source/wal.rst
> +                txn_region, txn_on_journal_write, txn);
The write itself is done in `journal_write` a couple of lines below. Let's mention it here, otherwise it's not clear what this code block illustrates.

2022-10-10 15:21 UTC, sergepetrenko commented on source/cbus.rst
> +It provides the user with message consumers (endpoints) and producers (pipes).
Anyone who calls `cpipe_push` from the input thread is a producer

2022-10-12 03:50 UTC, Serpentian commented on source/cbus.rst
> +Cbus (Communication bus)
It was mentioned in the wal docs, we're trying to update here. You can find it in deleted parts of the current PR. 

The question is whether it is really communication bus or not: I coudn't find any other mention of the module's full name. However, it sounds pretty meaningfully. Do we want to preserve these decodings (communication bus and communication pipes)?

2022-10-12 03:57 UTC, Serpentian commented on source/wal.rst
> +                txn_region, txn_on_journal_write, txn);
You're right. Fixed

2022-10-12 03:58 UTC, Serpentian commented on source/cbus.rst
> +It provides the user with message consumers (endpoints) and producers (pipes).
Fixed

2022-10-12 03:58 UTC, Serpentian commented on source/cbus.rst
> +by ``cbus_loop``. Let's consider in details the aforementioned entities.
Fixed

2022-10-12 04:05 UTC, Serpentian commented on source/cbus.rst
> +current hop and dispatch it to the next hop.
Added

2022-10-12 04:08 UTC, Serpentian commented on source/cbus.rst
> +In order to enter the event loop ``cbus_loop`` can be used:
I meant event loop of the `cbus`. Your proposal sounds better, so fixed

2022-10-12 13:43 UTC, sergepetrenko commented on source/cbus.rst
> +Cbus (Communication bus)
Let's leave the decoding here. Sounds meaningful, indeed.

2022-10-17 08:13 UTC, merged