fiber: update documentation
tarantool/tarantool-internals pull request #39
Opened 2022-10-17 10:48 UTC by Serpentian

Co-authored-by: Sergey Petrenko <sergepetrenko@tarantool.org>

2022-10-21 11:40 UTC, sergepetrenko requested changes
Thanks for working on this!

By the way, you don't have to mention me in `Co-authored-by`. I'm merely reviewing your work :)

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
>  provides to programmers. The service call supports ``waittime`` timeout,
'provides' -> 'provided'. Let's fix this typo as well

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +    /* libev/ev.c */
As I understand, you omit the `src/` part for files in `./src/whatever`.
Let's paste the full path here then (like `./third_party/libev/ev.c`)

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +        /* Fibers, ready for execution */
Extraneous comma.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +	    /* The "main" fiber of this cord, the scheduler. */
Some extra tabs slipped in here and 2 lines above.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +   replicas. Both of the cords communicates (see :ref:`cbus`) with iproto
Actually neither of them communicate with "iproto".

Relay communicates with tx and wal, and applier communicates solely with tx.
The only time when iproto is involved in replication, is when it passes a replication request received from the replica to tx thread.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +   result to the client.
It seems a diagram is needed here.

I'd draw typical paths for some common requests.
For example, for a ddl request coming from the net the path would look like:

Iproto (decode request) -> tx (process the request and prepare for commit) -> wal (write the request to journal) -> tx (process request result) -> iproto (send the answer to the client).

For applier and relay it would be:
on replica side: applier (receive a request from master & decode it) -> tx (apply the request) -> wal ... and so on.

For relay it would be tx(process a request) -> wal (write the request) -> relay (resend the request to replica).

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +	    /* The list of fibers awaiting for this fiber's death */
Extra tabs here and a couple of lines above.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
>  .. code-block:: c
There's the `sched` fiber description a couple of lines above. Let's mention that the `sched` fiber can't yield there.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +and reschedule then:
I couldn't understand this paragraph. Not sure that it's correct. Maybe it's better to simply remove it.

2022-10-21 11:40 UTC, sergepetrenko commented on source/fiber.rst
> +immediately though, event feeding means that we've put it into
I think we may drop the 2 paragraphs above. They go into libev details and don't explain anything IMO.

2022-10-24 08:38 UTC, Serpentian commented on source/fiber.rst
>  provides to programmers. The service call supports ``waittime`` timeout,
Actually, 'provides' sounds much more natural. ``libev`` did provide the API in the past, is providing it at the present, and will provide  it in the future. Present Simple is the best variant right here, I suppose. If you don't insist, I won't change it

2022-10-24 08:42 UTC, Serpentian commented on source/fiber.rst
> +    /* libev/ev.c */
Sounds reasonable. Fixed

2022-10-24 08:43 UTC, Serpentian commented on source/fiber.rst
> +        /* Fibers, ready for execution */
You're right, fixed

2022-10-24 08:44 UTC, Serpentian commented on source/fiber.rst
> +	    /* The "main" fiber of this cord, the scheduler. */
My bad, fixed

2022-10-24 08:44 UTC, Serpentian commented on source/fiber.rst
> +	    /* The list of fibers awaiting for this fiber's death */
My bad, fixed

2022-10-24 09:43 UTC, Serpentian commented on source/fiber.rst
> +   replicas. Both of the cords communicates (see :ref:`cbus`) with iproto
Thanks for the explanation, you're right. Fixed

2022-10-24 12:45 UTC, Serpentian commented on source/fiber.rst
> +   result to the client.
Done

2022-10-24 12:46 UTC, sergepetrenko commented on source/fiber.rst
>  provides to programmers. The service call supports ``waittime`` timeout,
Yep, I misread that. The current version sounds fine.

2022-10-24 15:07 UTC, Serpentian commented on source/fiber.rst
> +   replicas. Both of the cords communicates (see :ref:`cbus`) with iproto
You're right, fixed

2022-10-24 15:15 UTC, Serpentian commented on source/fiber.rst
> +and reschedule then:
Rewrited this paragraph

2022-10-24 15:27 UTC, Serpentian commented on source/fiber.rst
> +immediately though, event feeding means that we've put it into
Yeah, let's just refer to the `libev`'s manual.

2022-10-25 09:13 UTC, NickVolynkin commented on source/fiber.rst
> +cord is created the ``sched`` is initialized manually.
To make the source more readable and better diffable, start sentences on new lines. https://www.tarantool.io/en/doc/latest/contributing/docs/markup/intro/#wrapping-text

 ```suggestion
Each cord has a statically allocated scheduler fiber.
Note that ``cord->sched`` is not a pointer but an embedded complete structure.
So when a cord is created the ``sched`` is initialized manually.
```

2022-10-25 10:03 UTC, sergepetrenko commented on source/fiber.rst
> +of the current fiber:
Much better this time, now I understand. `fiber_loop` also helps `sched` to reuse already created fibers (they are parked in `cord->dead` list, and if the list is not empty, `fiber_new` takes one of the existing fibers from `cord->dead` rather than allocating and populating a new structure.

2022-10-25 10:05 UTC, sergepetrenko commented on source/fiber.rst
> +calls (see ``man libev``).
Do you have `man libev` locally? I don't. Maybe direct the user to its site? (http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod)

2022-10-25 10:10 UTC, sergepetrenko commented on source/fiber.rst
> +in SEGFAULT.
Let's also mention that same stands for any `libev` callbacks, and, for instance, cbus endpoint callbacks, like `tx_prio_cb`, and `fiber_pool_cb`

2022-10-25 10:18 UTC, sergepetrenko commented on source/fiber.rst
> +                  Relay thread <-------------------> WAL thread
Looks like applier thread's connected to WAL, and it isn't.

2022-10-26 04:28 UTC, Serpentian commented on source/fiber.rst
> +   it into a special structure.
Done. Looks much cleaner. Thanks for the link: it seems to be very useful

2022-10-26 04:33 UTC, Serpentian commented on source/fiber.rst
> +cord is created the ``sched`` is initialized manually.
Thanks, I'll try to follow this rule while writing docs in the future. But I've no great desire to change all internal docs according to it right now

2022-10-26 04:51 UTC, Serpentian commented on source/fiber.rst
> +of the current fiber:
Added

2022-10-26 04:58 UTC, Serpentian commented on source/fiber.rst
> +calls (see ``man libev``).
I do. It looks like that: [``man libev``](https://linux.die.net/man/3/ev). Also added the link to the site.

2022-10-26 05:26 UTC, Serpentian commented on source/fiber.rst
> +in SEGFAULT.
Done

2022-10-26 05:27 UTC, Serpentian commented on source/fiber.rst
> +                  Relay thread <-------------------> WAL thread
You're right. Fixed

2022-10-31 06:55 UTC, sergepetrenko approved these changes
Good job, LGTM.

2022-10-31 08:54 UTC, merged